/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package axoloti.dialogs;

import axoloti.Axoloti;
import axoloti.MainFrame;
import static axoloti.MainFrame.prefs;
import axoloti.utils.AxoFileLibrary;
import axoloti.utils.AxoGitLibrary;
import axoloti.utils.AxolotiLibrary;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author kodiak
 */
public class AxolotiLibraryEditor extends javax.swing.JDialog {

    private AxolotiLibrary library;

    /**
     * Creates new form AxolotiLibrary
     *
     * @param parent
     * @param modal
     */
    public AxolotiLibraryEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        library = new AxolotiLibrary();
        populate();
        setVisible(true);
    }

    public AxolotiLibraryEditor(java.awt.Frame parent, boolean modal, AxolotiLibrary lib) {
        super(parent, modal);
        initComponents();
        library = lib;
        populate();
        jId.setEnabled(false);
        setVisible(true);
    }

    final void populate() {
        jId.setText(library.getId());
        jEnabled.setSelected(library.getEnabled());
        jLocalDir.setText(library.getLocalLocation());
        jRemotePath.setText(library.getRemoteLocation());
        jUserId.setText(library.getUserId());
        jPassword.setText(library.getPassword());
        jAutoSync.setSelected(library.isAutoSync());
        jRevision.setText(library.getRevision());
        jPrefix.setText(library.getContributorPrefix());

        String[] types = {AxoFileLibrary.TYPE, AxoGitLibrary.TYPE};
        jTypeCombo.removeAllItems();
        for (String t : types) {
            jTypeCombo.addItem(t);
        }
        jTypeCombo.setSelectedItem(library.getType());

        boolean expert = MainFrame.prefs.getExpertMode() || Axoloti.isDeveloper();
        boolean lockDown
                = !expert
                && ((AxolotiLibrary.FACTORY_ID.equals(library.getId()))
                || (AxolotiLibrary.USER_LIBRARY_ID.equals(library.getId())));
        jRevision.setEditable(!lockDown);
        jRemotePath.setEditable(!lockDown);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTypeCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLocalDir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRemotePath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jUserId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jEnabled = new javax.swing.JCheckBox();
        jPassword = new javax.swing.JPasswordField();
        jOK = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jInitRepo = new javax.swing.JButton();
        jAutoSync = new javax.swing.JCheckBox();
        jSelectDirBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 3), new java.awt.Dimension(0, 3), new java.awt.Dimension(32767, 3));
        jLabel8 = new javax.swing.JLabel();
        jRevision = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPrefix = new javax.swing.JTextField();
        jSyncBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTypeCombo.setPreferredSize(new java.awt.Dimension(100, 28));
        jTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        jId.setMinimumSize(new java.awt.Dimension(100, 28));
        jId.setPreferredSize(new java.awt.Dimension(100, 28));

        jLocalDir.setPreferredSize(new java.awt.Dimension(400, 28));

        jLabel2.setText("Id");

        jLabel3.setText("Directory");

        jRemotePath.setPreferredSize(new java.awt.Dimension(400, 28));

        jLabel4.setText("Remote Path");

        jLabel5.setText("Remote Library");

        jUserId.setMinimumSize(new java.awt.Dimension(14, 50));
        jUserId.setPreferredSize(new java.awt.Dimension(150, 28));

        jLabel6.setText("User Id");

        jLabel7.setText("Password");

        jEnabled.setText("Enabled");

        jPassword.setText("jPasswordField1");
        jPassword.setPreferredSize(new java.awt.Dimension(150, 28));

        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        jCancel.setText("Cancel");
        jCancel.setDefaultCapable(false);
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jInitRepo.setText("Init");
        jInitRepo.setDefaultCapable(false);
        jInitRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInitRepoActionPerformed(evt);
            }
        });

        jAutoSync.setText("Auto Sync");

        jSelectDirBtn.setText("Select");
        jSelectDirBtn.setDefaultCapable(false);
        jSelectDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectDirBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Revision");

        jRevision.setMinimumSize(new java.awt.Dimension(100, 28));
        jRevision.setPreferredSize(new java.awt.Dimension(100, 28));

        jLabel9.setText("Contributors only:");

        jLabel10.setText("(optional)");

        jLabel11.setText("Contributor Prefix");

        jPrefix.setPreferredSize(new java.awt.Dimension(100, 28));

        jSyncBtn.setText("Sync");
        jSyncBtn.setDefaultCapable(false);
        jSyncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSyncBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOK))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jAutoSync))
                                    .addComponent(jRemotePath, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInitRepo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSyncBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(104, 104, 104)
                                        .addComponent(jEnabled))
                                    .addComponent(jLocalDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSelectDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 306, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 306, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jEnabled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLocalDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSelectDirBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRemotePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInitRepo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAutoSync)
                    .addComponent(jLabel10)
                    .addComponent(jSyncBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOK)
                    .addComponent(jCancel))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 198, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 198, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeComboActionPerformed
    }//GEN-LAST:event_jTypeComboActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        if (jId.getText() == null || jId.getText().length() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Id is required, and must be unique",
                    "Invalid Library",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jLocalDir.getText() == null || jLocalDir.getText().length() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Local directory is required, and must be valid",
                    "Invalid Library",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jId.getText().equals(AxolotiLibrary.USER_LIBRARY_ID)
                && (jUserId.getText() != null && jUserId.getText().length() > 0)) {
            char[] p = jPassword.getPassword();
            if ((jPrefix.getText() == null || jPrefix.getText().length() == 0)
                    || (p == null || p.length == 0)) {
                JOptionPane.showMessageDialog(this,
                        "Contributors for the community library need to specify username, password and prefix",
                        "Invalid Library",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        populateLib(library);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jOKActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jInitRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInitRepoActionPerformed
        boolean delete;
        int options = JOptionPane.OK_CANCEL_OPTION;
        int res = JOptionPane.showConfirmDialog(this, "Init will delete existing directory\n Continue?", "Warning", options);
        if (res == JOptionPane.CANCEL_OPTION) {
            return;
        }
        delete = (res == JOptionPane.OK_OPTION);

        AxoGitLibrary gitlib = new AxoGitLibrary();
        populateLib(gitlib);
        gitlib.init(delete);
    }//GEN-LAST:event_jInitRepoActionPerformed

    private void jSelectDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectDirBtnActionPerformed
        String dir = jLocalDir.getText();
        if (dir == null || dir.length() == 0) {
            dir = prefs.getCurrentFileDirectory();
        }

        File seldir = new File(dir).getParentFile();
        JFileChooser fc = new JFileChooser(seldir);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory();
            }

            @Override
            public String getDescription() {
                return "Any folder";
            }
        });

        fc.setDialogTitle("Select Directory");
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        fc.setApproveButtonText("Select");
        ArrayList<JPanel> jpanels = new ArrayList<JPanel>();
        for (Component c : fc.getComponents()) {
            if (c instanceof JPanel) {
                jpanels.add((JPanel) c);
            }
        }
        jpanels.get(0).getComponent(0).setVisible(false);
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            seldir = fc.getSelectedFile();
            if (!seldir.exists()) {
                seldir = seldir.getParentFile();
            }
            try {
                dir = seldir.getCanonicalPath();
                jLocalDir.setText(dir + File.separator);
            } catch (IOException ex) {
                Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jSelectDirBtnActionPerformed

    private void jSyncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSyncBtnActionPerformed
        AxoGitLibrary gitlib = new AxoGitLibrary();
        populateLib(gitlib);
        gitlib.sync();
    }//GEN-LAST:event_jSyncBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox jAutoSync;
    private javax.swing.JButton jCancel;
    private javax.swing.JCheckBox jEnabled;
    private javax.swing.JTextField jId;
    private javax.swing.JButton jInitRepo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLocalDir;
    private javax.swing.JButton jOK;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jPrefix;
    private javax.swing.JTextField jRemotePath;
    private javax.swing.JTextField jRevision;
    private javax.swing.JButton jSelectDirBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jSyncBtn;
    private javax.swing.JComboBox jTypeCombo;
    private javax.swing.JTextField jUserId;
    // End of variables declaration//GEN-END:variables

    public AxolotiLibrary getLibrary() {
        return library;
    }

    public void setLibrary(AxolotiLibrary library) {
        this.library = library;
    }

    private void populateLib(AxolotiLibrary library) {
        library.setId(jId.getText().trim());
        library.setLocalLocation(jLocalDir.getText().trim());
        library.setRemoteLocation(jRemotePath.getText().trim());
        library.setUserId(jUserId.getText().trim());
        library.setPassword(new String(jPassword.getPassword()));
        library.setEnabled(jEnabled.isSelected());
        library.setType((String) jTypeCombo.getSelectedItem());
        library.setAutoSync(jAutoSync.isSelected());
        library.setContributorPrefix(jPrefix.getText().trim());
        library.setRevision(jRevision.getText().trim());
    }
}
