package axoloti.dialogs;

import axoloti.CConnection;
import axoloti.ConnectionStatusListener;
import axoloti.DocumentWindow;
import axoloti.IConnection;
import axoloti.menus.StandardMenubar;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author jtaelman
 */
public class Memory extends javax.swing.JFrame implements ActionListener, ConnectionStatusListener, DocumentWindow {

    /**
     * Creates new form Memory
     */
    public Memory() {
        initComponents();
        setJMenuBar(new StandardMenubar());
        setIconImage(new ImageIcon(getClass().getResource("/resources/axoloti_icon.png")).getImage());
        jTextFieldAddr.setFont(Font.getFont(Font.MONOSPACED));
        jTextAreaMemoryContent.setFont(Font.getFont(Font.MONOSPACED));
        jTextAreaMemoryContent.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAddr = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonInc = new javax.swing.JButton();
        jButtonDec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMemoryContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel1.setText("Address:");

        jTextFieldAddr.setText("0x00000000");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonInc.setText("+0x100");
        jButtonInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncActionPerformed(evt);
            }
        });

        jButtonDec.setText("-0x100");
        jButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInc)
                    .addComponent(jButtonDec)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaMemoryContent.setColumns(20);
        jTextAreaMemoryContent.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMemoryContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void readmem(int addr) {
        this.addr = addr;
        jTextFieldAddr.setText(String.format("0x%08x", addr));
        jTextAreaMemoryContent.setFont(new Font("monospaced", Font.PLAIN, 12));
        int length = 256;
        CConnection.GetConnection().TransmitMemoryRead(addr, length, new IConnection.MemReadHandler() {
            @Override
            public void Done(ByteBuffer mem) {
                String s = "";
                for (int i = 0; i < (length / 16); i++) {
                    int v1 = mem.getInt();
                    int v2 = mem.getInt();
                    int v3 = mem.getInt();
                    int v4 = mem.getInt();
                    s += String.format("%08x : %08x %08x %08x %08x\n", addr + (i * 16), v1, v2, v3, v4);
                }
                jTextAreaMemoryContent.setText(s);
            }
        });
    }

    int addr = 0;

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        String hex = jTextFieldAddr.getText();
        if (hex.startsWith("0x")) {
            hex = hex.substring(2);
        }
        addr = (new BigInteger(hex, 16)).intValue();
        readmem(addr);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncActionPerformed
        readmem(addr + 0x100);
    }//GEN-LAST:event_jButtonIncActionPerformed

    private void jButtonDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecActionPerformed
        readmem(addr - 0x100);
    }//GEN-LAST:event_jButtonDecActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
    }

    @Override
    public void ShowConnect() {
    }

    @Override
    public void ShowDisconnect() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDec;
    private javax.swing.JButton jButtonInc;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMemoryContent;
    private javax.swing.JTextField jTextFieldAddr;
    // End of variables declaration//GEN-END:variables

    @Override
    public JFrame GetFrame() {
        return this;
    }

    @Override
    public boolean AskClose() {
        return false;
    }

    @Override
    public File getFile() {
        return null;
    }

    @Override
    public ArrayList<DocumentWindow> GetChildDocuments() {
        return null;
    }
}
