#define object files in the module

MOD_PRE = header_pre.h

MOD_OBJS = \
       warps/dsp/filter_bank.o \
       warps/dsp/modulator.o \
       warps/dsp/oscillator.o \
       warps/dsp/vocoder.o 



