#define object files in the module

MOD_PRE = header_pre.h

MOD_OBJS = \
       clouds/dsp/correlator.o \
       clouds/dsp/mu_law.o \
       clouds/dsp/granular_processor.o \
       clouds/dsp/pvoc/frame_transformation.o \
       clouds/dsp/pvoc/phase_vocoder.o \
       clouds/dsp/pvoc/stft.o



